[project]
name = "worker"
version = "0.1.0"
description = "IsoQuaC Job Worker"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "boto3>=1.42.22",
    "docker>=7.1.0",
    "redis>=7.1.0",
]

[dependency-groups]
dev = [
    "ruff>=0.14.10",
    "ty>=0.0.9",
]
